steps:
  # Step 1: Build and push Docker image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "buildx",
        "build",
        "--platform",
        "linux/amd64",
        "-t",
        "gcr.io/cloud-429207/container_1:latest",
        "--push",
        ".",
      ]

  # Step 2: Set up Kubernetes CLI (kubectl)
  - name: "gcr.io/cloud-builders/kubectl"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        # Get the GKE cluster credentials
        gcloud container clusters get-credentials [CLUSTER_NAME] --zone [CLUSTER_ZONE] --project [PROJECT_ID]

images:
  - "gcr.io/cloud-429207/container_1:latest"

options:
  logging: CLOUD_LOGGING_ONLY
